### ISSUE TITLE
Quality of Life Improvements

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#53]
Hey Andy,

As I mentioned in c.s.a2 6502bench has an _excellent_ foundation to build upon. However there are several QoL (Quality of Life) enhancements that would immensely speed up my "Apple ][ Games Disassembly Projects" (and I bet other people's workflow) as they reverse engineer and disassemble Apple ][ software.  Anything that lets me _avoid_ more (excessive) mouse clicking and let me use the left hand for keyboard shortcuts is the prime motivation.

This is my master list of UI enhancements.  It will be added to over time to make it easy to see what is done and what needs to be done. (Apparently forking doesn't let me track my _own_ issues thus I need to create it here.)

* [ ] #54 `Set Address` (key)
* [ ] #55 `Code Entry Point` (key)
* [ ] #56 `Create/Edit Visualization New Bitmap` (key)
* [x] #57 `New Bitmap` accelerator (key)
* [ ] #58 `Inline Data` (key)
* [x] #59 `Instruction Chart` (uppercase)
* [x] #60 `Instruction Chart` (hide invalid)
* [ ] #61 `Instruction Chart` (hex input/find)
* [ ] #62 `Disassembly window` (vertical split)
* [ ] #63 `Smart Go To`
* [ ] #64 `Code Entry Point` -> `Function` (cosmetic)
* [ ] #65 `Show Hex Dump` (key)
* [ ] #66 `Create Smart Label`
* [x] #67 `Strings` (accelerator)
* [ ] #68 `Strings` (count)
* [ ] #69 `Inline Data String` (key)
* [ ] #70 `Smart String`
* [ ] #71 `String Control Characters`
* [ ] #72 `Smart Navigate` (key)
* [ ] #73 `Bookmarks` (keys)
* [x] #74 `Visualize Bitmap` (dimensions)
* [ ] #75 `Visualizer Font` (dimensions)
* [x] #76 `Visualizer High-bit` (blue/orange)
* [ ] #77 `AppleWin Debugger Support`

# Documentation

* [ ] Update ` SourceNotes` with detailed instructions installing Visual Studio 2019
* [ ] Update Tutorial documenting _Lode Runner_ that shows most of the important features of 6502bench

# Optional

* [x] #79 `Instruction Chart` extra features  (marked as done to keep the the tally accurate for the important stuff above)

**Comment by fadden** [comment]
Migrating feature requests to [wiki](https://github.com/fadden/6502bench/wiki/TO-DO-List).

**Comment by fadden** [comment]
> Apparently forking doesn't let me track my own issues thus I need to create it here

FWIW, if you click Settings on the project page and scroll down to Features, you should be able to enable Issues in the fork.

&lt;/necro&gt;
